name: Build and Deploy Docker App to Azure Web App

on:
  push:
    branches:
      - main # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to container registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.AZURE_CONTAINER_REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ secrets.AZURE_WEBAPP_NAME }}:${{ github.sha }} ./server/DockerFile

      - name: Push Docker image
        run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ secrets.AZURE_WEBAPP_NAME }}:${{ github.sha }}

      - name: Deploy to Azure Web App (Docker)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ secrets.AZURE_WEBAPP_NAME }}:${{ github.sha }}
